version: '3.8'

services:
  # nosemgrep: yaml.docker-compose.security.writable-filesystem-service.writable-filesystem-service
  cloud-drive:
    build: .
    container_name: cloud_drive_app
    ports:
      - "5001:5000"
    volumes:
      - ./data/encrypted:/data/encrypted
      - ./data/temp:/data/temp
    environment:
      - FLASK_HOST=0.0.0.0
      - UPLOAD_FOLDER=/data/encrypted
      - TEMP_FOLDER=/data/temp
    restart: unless-stopped
    networks:
      - cloud_drive_network
    security_opt:
      - no-new-privileges:true

  # nosemgrep: yaml.docker-compose.security.writable-filesystem-service.writable-filesystem-service
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared_persistent
    command: tunnel --config /etc/cloudflared/config.yml run
    volumes:
      - ./cloudflared_config:/etc/cloudflared:ro
    networks:
      - cloud_drive_network
    depends_on:
      - cloud-drive
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true  

networks:
  cloud_drive_network:
    driver: bridge
